### ISSUE TITLE
How to manage the server(asking prior installation)

### ISSUE THREAD

**Issue by mzltest** [Shirakumo/ex-lichat#1]
First just surfing the web and found this project.All looks attractive to me and thanks for continuous commiting on the project.
However although I saw readmes and configuration files that allows installation of the server,I didn't see guides for administrative actions.
I'd appreciate it if you can point out how to achieve the following actions:
- [ ] How to claim server admin role after spinning up the server
- [ ] How to do server management actions.Is it a special command or some interface?
- And finally,just to satisfy my curiosity,is the supported plugins in the readme already installed or where should I go to get these plugins and how to install them?

**Comment by Shinmera** [comment]
For server admin you can simply use the elixir console and invoke the respective functions, such as `Channel.make_admin`, `Channel.grant`, etc. Once permissions have been granted, some server administration can also be performed through the Lichat protocol using the `shirakumo-server-management` extension among others.

The extensions list is the list of specified protocol extensions that the server supports out of the box. There's no plugin mechanism at all at the moment.
